name: Test Action
on:
  workflow_dispatch:
    branches:
      - main

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test action
        uses: ./
        with:
          mta: './test.mtar'
          credentials: ${{ secrets.CREDENTIALS }}
          namedUser: GitHubAcions
          nodeName: DEV
          transportDescription: 'test'