name: Test Action
on: workflow_dispatch

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Upload MTA to CTMS
        uses: ./
        with:
          mta: './test.mtar'
          credentials: ${{ secrets.CTMS_CREDENTIALS }}
          namedUser: GitHubActions
          nodeName: DEV
          transportDescription: 'test'
          importTransportRequest: true